#!/usr/bin/env bash
#
# A JSPkg bash script
permalink(){
  local lc="$(tr [A-Z] [a-z] <<< "$@")"
  echo ${lc//[^a-z]/-}
}

download(){
  local project=$1
  echo "downloading $project"
  `curl -L -# -C - -o $project.zip http://jshub.dev/packages/$project/download/`
}

unpack(){
  local project=$1
  echo "unpacking $project.zip"
  unzip -d $project $project.zip
}

remove() {
  local project=$1
  echo "cleaning up $project.zip"
  `rm $project.zip`
}

install(){
  local project="$(permalink $1)"

  download $project

  unpack $project

  remove $project

  echo "downloaded and unpacked to \"$project/\" directory :-)"
}

case "$1" in
  'permalink')
    shift 1
    permalink $@
    exit
    ;;
  'download')
    shift 1
    download $@
    exit
    ;;
  'unpack')
    shift 1
    unpack $@
    exit
    ;;
  'remove')
    shift 1
    remove $@
    exit
    ;;
esac

install $2
