#!/usr/bin/env bash
#
# A JSPkg bash script
permalink(){
  local lc="$(tr [A-Z] [a-z] <<< "$@")"
  echo ${lc//[^a-z]/-}
}

download(){
  local project=$1
  echo "downloading $project"
  `curl -L -# -C - -o $project.zip http://jshub.dev/packages/$project/download/`
}

install(){
  local project=$1

  download $project

  echo "unpacking $project.zip"
  `unzip -d $project $project.zip`

  echo "cleaning up $project.zip"
  `rm $project.zip`

  echo "downloaded and unpacked to \"$project/\" directory :-)"
}

case "$1" in
  'permalink')
    shift 1
    permalink $@
    exit
    ;;
  'download')
    shift 1
    download $@
    exit
    ;;
esac

install $2
